### ISSUE TITLE
关于该项目中部分方法命名的建议

### ISSUE THREAD

**Issue by HughTang** [aoju/lancia#15]
尊敬的开发者：
    您好！非常感谢您能抽出宝贵的时间来阅读此Issue，我们是来自西北工业大学软件学院硕士课题组的科研团队，正在进行一项关于Java开源项目中方法（函数）名称一致性检查和建议的科研研究，方法（函数）名称的可读性对开发人员理解代码至关重要，我们将本开源项目作为我们研发工具DMName的实验验证对象，共发现了以下存在的16个方法（函数）命名问题，原始的建议修改的方法名称是第3列original_name，建议的方法名称为第4列suggest_name：
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

path | line | original_name | suggest_name
-- | -- | -- | --
lancia/src/main/java/org/aoju/lancia/Browser.java | 170 | create | createBrowser
lancia/src/main/java/org/aoju/lancia/Browser.java | 237 | targetCreated | createTargetByEvent
lancia/src/main/java/org/aoju/lancia/Browser.java | 263 | waitForTarget | initialTarget
lancia/src/main/java/org/aoju/lancia/Browser.java | 284 | target | getTarget 
lancia/src/main/java/org/aoju/lancia/Browser.java | 336 | find | findTargetByPredicate
lancia/src/main/java/org/aoju/lancia/Builder.java | 363 | printPDF | fileIOStreamHandle
lancia/src/main/java/org/aoju/lancia/Builder.java | 551 | evaluationString | evaluteJsonString 
lancia/src/main/java/org/aoju/lancia/Builder.java | 674 | download | downloadFile
lancia/src/main/java/org/aoju/lancia/kernel/browser/Fetcher.java | 628 | revisionInfo | getReversionInfo
lancia/src/main/java/org/aoju/lancia/kernel/browser/Fetcher.java | 677 | archiveName | parseArchiveName
lancia/src/main/java/org/aoju/lancia/worker/SocketTransport.java | 190 | createBinary | createBufferBlock
lancia/src/main/java/org/aoju/lancia/worker/SocketTransport.java | 229 | translate | translateBuffer
lancia/src/main/java/org/aoju/lancia/worker/SocketTransport.java | 279 | translatePayload | translateBufferByPayload
lancia/src/main/java/org/aoju/lancia/worker/SocketTransport.java | 300 | translateSingle | translateSingleBuffer
lancia/src/main/java/org/aoju/lancia/worker/SocketTransport.java | 882 | reset | resetConnection
lancia/src/main/java/org/aoju/lancia/worker/SocketTransport.java | 993 | runWrite | writeToOutstream

</body>

</html>

如果您认可或反对上述所涉及的问题和命名建议，可以发邮件（[hughtang@mail.nwpu.edu.cn](mailto:hughtang@mail.nwpu.edu.cn)）联系我们或直接在本Issue下回复，我们由衷地希望能够得到您宝贵的意见反馈，期待您的回复！

**Comment by 839536** [comment]
感谢提供建议，这里面的方法名称参考[Puppeteer](https://github.com/GoogleChrome/puppeteer) 的相关api设计，如果修改相应方法名称，会出现与Puppeteer方法不一致的问题，再次感谢
